### ISSUE TITLE
Agregar Datos abiertos de RECOPE

### ISSUE THREAD

**Issue by kevinah95** [ruiznorlan/public-apis-cr#1]
Este es el enlace de datos abiertos de RECOPE:

[Datos abiertos RECOPE](https://datosabiertos.recope.go.cr/servicio-api)

**Comment by ruiznorlan** [comment]
Listo, gracias 🫡

[[ADD] RECOPE: API](https://github.com/ruiznorlan/public-apis-cr/commit/fdc2aca22fa57a03b3e09e198a62c287f76d595c)

**Comment by kevinah95** [comment]
Gracias a vos Norlan. 

¡Qué Tuanis!

🇨🇷
